services:
  - type: web
    plan: free
    name: FADEDMUSIC
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 server.py & python3 -m FADEDMUSIC 
 repo:
https://github.com/Destroyerofworldd/Destroyer_music   
    branch: master
    envVars:
      - key: SUDO_USERS 
        sync: false
      - key: BOT_TOKEN 
        sync: false
      - key: OWNER_ID 
        sync: 7557718680
      - key: STRING_SESSION
        sync: false
      - key: MONGO_URL
        sync: false    
      - key: STRING_SESSION
        sync: false   
      - key: API_ID
        sync: false   
      - key: API_HASH
        sync: false    
    autoDeploy: false
